// assets/javascript/pegasus/examples/react/EmployeeTableRow.js
import React from "react";
import {Link} from "react-router-dom";

const EmployeeTableRow = function (props) {
  const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  });
  return (
    <tr>
      <td>{props.name}</td>
      <td>{props.department}</td>
      <td className="has-text-right">{ formatter.format(props.salary) }</td>
      <td className="has-text-right">
        <Link to={`/edit/${props.id}`}>
          <div className="button is-primary is-outlined">
            <span className="icon is-small"><i className="fa fa-edit" /></span>
            <span>Edit</span>
          </div>
        </Link>
        <a style={{'marginLeft': '1em'}} onClick={() => props.delete(props.index)}>
          <div className="button is-text">
            <span>Delete</span>
          </div>
        </a>
      </td>
    </tr>
  );
}

export default EmployeeTableRow;

// {{cookiecutter.project_slug}}/assets/javascript/pegasus/examples/vue/components/EmployeeTableRow.vue
<template>
  <tr>
    <td>{{ employee.name }}</td>
    <td>{{ employee.department }}</td>
    <td class="has-text-right">{{ formattedSalary }}</td>
    <td class="has-text-right">
      <a class="button is-primary is-outlined" v-on:click="editEmployee">
        <span class="icon is-small"><i class="fa fa-edit" /></span>
        <span>Edit</span>
      </a>
      <a class="button is-text" v-on:click="deleteEmployee">
        <span>Delete</span>
      </a>
    </td>
  </tr>
</template>

<script>

export default {
  name: 'EmployeeTableRow',
  props: {
    employee: Object,
    client: Object,
  },
  computed: {
    formattedSalary: function () {
      const formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
      });
      return formatter.format(this.employee.salary);
    }
  },
  methods: {
    editEmployee: function () {
      this.$emit('edit-employee', this.employee);
    },
    deleteEmployee: function () {
      this.$emit('delete-employee', this.employee);
    },
  }
};
</script>

<style scoped>
</style>
